from __future__ import annotations

from typing import Any

MODULE_REGISTRY: tuple[dict[str, Any], ...] = (
    {
        "id": "dashboard",
        "title": "Главная / Системный мозг",
        "version": "01.13.00",
        "area": "system",
        "description": "Real-time дашборд состояния, архитектуры, памяти, нагрузки и активных процессов.",
        "last_update": "Системный мозг и настройки дополнены Cognitive Core IX и безопасным машиночитаемым отчётом самодиагностики.",
        "depends_on": ["memory", "grey_matter", "cognition", "drive", "updater"],
    },
    {
        "id": "drive",
        "title": "Мой диск",
        "version": "01.09.00",
        "area": "documents",
        "description": "Единое файловое пространство, папки, паспорта, ДНК, версии, поиск и связи.",
        "last_update": "Document Intelligence v2: chunk-first анализ больших файлов, проверки, evidence и улучшенное сравнение версий.",
        "depends_on": [],
    },
    {
        "id": "memos",
        "title": "Служебные записки",
        "version": "01.06.00",
        "area": "documents",
        "description": "Служебные записки, включая работу в выходной день и подготовку данных табеля.",
        "last_update": "Добавлены «Основные факты» с доказательствами, год/тема, автосортировка, копии/версии, шаблоны и AI-изучение в память проекта.",
        "depends_on": ["drive", "employees", "timesheet"],
    },
    {
        "id": "invoice_offers",
        "title": "Счета-оферты",
        "version": "01.05.00",
        "area": "documents",
        "description": "Счёт и краткие договорные условия в одном самостоятельном документе.",
        "last_update": "Изучение разрешённых счетов-оферт проходит через единый Memory Intake и Guardian.",
        "depends_on": ["drive"],
    },
    {
        "id": "contracts",
        "title": "Договоры",
        "version": "01.06.00",
        "area": "documents",
        "description": "Договоры по контрагентам с реквизитами, суммами, сроками и версиями.",
        "last_update": "Документный контекст изолирован как недоверенные данные; долговременные знания проходят через Guardian.",
        "depends_on": ["drive"],
    },
    {
        "id": "orders",
        "title": "Приказы",
        "version": "01.03.00",
        "area": "documents",
        "description": "Эталонные приказы предприятия и подготовка новых проектов в корпоративном стиле.",
        "last_update": "Reference-based ИИ по разрешённым образцам с изоляцией недоверенного содержимого документов.",
        "depends_on": ["drive", "employees"],
    },
    {
        "id": "directives",
        "title": "Распоряжения",
        "version": "01.03.00",
        "area": "documents",
        "description": "Эталонные распоряжения и подготовка новых проектов в стиле предприятия.",
        "last_update": "Reference-based ИИ по разрешённым образцам с защитой от indirect prompt injection.",
        "depends_on": ["drive", "employees"],
    },
    {
        "id": "employees",
        "title": "Сотрудники",
        "version": "01.00.00",
        "area": "reference",
        "description": "Справочник сотрудников, должностей, подразделений и рабочих реквизитов.",
        "last_update": "Новый модуль для документов, приказов и табеля.",
        "depends_on": [],
    },
    {
        "id": "garage",
        "title": "Гараж",
        "version": "01.03.00",
        "area": "reference",
        "description": "Автопарк: номера, VIN, водители, ГСМ, автошины и страхование.",
        "last_update": "Добавлены летняя/зимняя норма ГСМ, размеры шин и контроль страховки с предупреждением за 15 дней.",
        "depends_on": ["employees"],
    },
    {
        "id": "timesheet",
        "title": "Табель",
        "version": "01.05.00",
        "area": "work",
        "description": "Месячный табель: календарь РФ, ручные отпуск/больничный и работа в выходной из служебных записок.",
        "last_update": "Добавлены официальные производственные календари РФ 2026/2027, сетка Т-13-подобного вида и ручные коды ОТ/Б.",
        "depends_on": ["employees", "memos"],
    },
    {
        "id": "reasoning",
        "title": "Мышление Тоору",
        "version": "04.00.00",
        "area": "system",
        "description": "Планирование сложных задач, самопроверка результата и безопасное обучение на опыте.",
        "last_update": "Reasoning Router получает bounded self-learning policy и метакогнитивную эскалацию Chain/Tree/Hybrid.",
        "depends_on": ["memory", "grey_matter", "cognition"],
    },
    {
        "id": "cognition",
        "title": "Cognitive Core IX",
        "version": "02.00.00",
        "area": "system",
        "description": "Самообучающийся и самодиагностирующийся метакогнитивный слой: bounded reasoning policy, рабочий граф, проактивные инсайты и проверяемый технический снимок.",
        "last_update": "Self-Diagnostics & Explainability: полная техническая картина reasoning, памяти, Grey Matter, документов, автоматик и ошибок без экспорта скрытых рассуждений.",
        "depends_on": ["memory", "grey_matter", "reasoning", "drive", "garage"],
    },
    {
        "id": "diagnostics",
        "title": "Самодиагностика / Машинный отчёт",
        "version": "01.00.00",
        "area": "system",
        "description": "Безопасный JSON-снимок работы Dragon Tory для поиска ошибок в документах, AI, памяти, reasoning, cognition, автоматиках и обновлениях.",
        "last_update": "В Настройки добавлено скачивание полного support snapshot с document pipeline, provenance, health, policy и observability.",
        "depends_on": ["drive", "memory", "grey_matter", "reasoning", "cognition"],
    },
    {
        "id": "grey_matter",
        "title": "Серое вещество",
        "version": "02.00.00",
        "area": "system",
        "description": "Метакогнитивный слой: сущности, причинность, uncertainty, иерархия, цели, multi-hop, исправления и навыки.",
        "last_update": "Adaptive Grey Matter: стратегия поиска, калибровка доверия, кластеры противоречий, причинные веса и безопасное забывание.",
        "depends_on": ["memory", "reasoning"],
    },
    {
        "id": "memory",
        "title": "Память Тоору",
        "version": "03.02.00",
        "area": "system",
        "description": "Раздельная личная и проектная долговременная память, Guardian, поиск и обслуживание.",
        "last_update": "Явные исправления пользователя сохраняются как LESSON через Guardian; когнитивные метрики не смешиваются с долговременной памятью.",
        "depends_on": [],
    },
    {
        "id": "updater",
        "title": "Обновление",
        "version": "01.06.00",
        "area": "system",
        "description": "GitHub self-update, резервная копия, проверка, перезапуск и история.",
        "last_update": "Windows startup больше не блокируется установкой Tesseract/LibreOffice; системные движки проверяются после готовности backend.",
        "depends_on": [],
    },
)


def module_registry() -> list[dict[str, Any]]:
    return [dict(item) for item in MODULE_REGISTRY]
