from __future__ import annotations

from typing import Any

MODULE_REGISTRY: tuple[dict[str, Any], ...] = (
    {
        "id": "dashboard",
        "title": "Главная / Системный мозг",
        "version": "01.03.00",
        "area": "system",
        "description": "Real-time дашборд состояния, архитектуры, памяти, нагрузки и активных процессов.",
        "last_update": "Добавлен live observability: текущая работа Тоору, AI latency/retry, Guardian и цепочки источник → память.",
        "depends_on": ["memory", "drive", "updater"],
    },
    {
        "id": "drive",
        "title": "Мой диск",
        "version": "01.06.00",
        "area": "documents",
        "description": "Единое файловое пространство, папки, паспорта, ДНК, версии, поиск и связи.",
        "last_update": "Локальный анализ документов теперь формирует технические observability-события без сохранения текста документов.",
        "depends_on": [],
    },
    {
        "id": "memos",
        "title": "Служебные записки",
        "version": "01.04.00",
        "area": "documents",
        "description": "Служебные записки, включая работу в выходной день и подготовку данных табеля.",
        "last_update": "Защита образцов от prompt injection и автосинхронизация работы в выходной день в проектную память.",
        "depends_on": ["drive", "employees", "timesheet"],
    },
    {
        "id": "invoice_offers",
        "title": "Счета-оферты",
        "version": "01.04.00",
        "area": "documents",
        "description": "Счёт и краткие договорные условия в одном самостоятельном документе.",
        "last_update": "Изучение разрешённых счетов-оферт проходит через единый Memory Intake и Guardian.",
        "depends_on": ["drive"],
    },
    {
        "id": "contracts",
        "title": "Договоры",
        "version": "01.05.00",
        "area": "documents",
        "description": "Договоры по контрагентам с реквизитами, суммами, сроками и версиями.",
        "last_update": "Документный контекст изолирован как недоверенные данные; долговременные знания проходят через Guardian.",
        "depends_on": ["drive"],
    },
    {
        "id": "orders",
        "title": "Приказы",
        "version": "01.03.00",
        "area": "documents",
        "description": "Эталонные приказы предприятия и подготовка новых проектов в корпоративном стиле.",
        "last_update": "Reference-based ИИ по разрешённым образцам с изоляцией недоверенного содержимого документов.",
        "depends_on": ["drive", "employees"],
    },
    {
        "id": "directives",
        "title": "Распоряжения",
        "version": "01.03.00",
        "area": "documents",
        "description": "Эталонные распоряжения и подготовка новых проектов в стиле предприятия.",
        "last_update": "Reference-based ИИ по разрешённым образцам с защитой от indirect prompt injection.",
        "depends_on": ["drive", "employees"],
    },
    {
        "id": "employees",
        "title": "Сотрудники",
        "version": "01.00.00",
        "area": "reference",
        "description": "Справочник сотрудников, должностей, подразделений и рабочих реквизитов.",
        "last_update": "Новый модуль для документов, приказов и табеля.",
        "depends_on": [],
    },
    {
        "id": "garage",
        "title": "Гараж",
        "version": "01.02.00",
        "area": "reference",
        "description": "Справочник автомобилей, водителей, гаражных номеров, госномеров и VIN.",
        "last_update": "Изменения автомобиля автоматически и локально синхронизируются в проектную память через Guardian.",
        "depends_on": ["employees"],
    },
    {
        "id": "timesheet",
        "title": "Табель",
        "version": "01.04.00",
        "area": "work",
        "description": "Свод рабочих часов, включая работу в выходной день из служебных записок.",
        "last_update": "Работа в выходной день автоматически обновляет проектную память при сохранении ДНК и из чата.",
        "depends_on": ["employees", "memos"],
    },
    {
        "id": "memory",
        "title": "Память Тоору",
        "version": "01.05.00",
        "area": "system",
        "description": "Раздельная личная и проектная долговременная память, Guardian, поиск и обслуживание.",
        "last_update": "Guardian и Memory Intake публикуют решения, блокировки и Memory ID в единую трассу наблюдаемости.",
        "depends_on": [],
    },
    {
        "id": "updater",
        "title": "Обновление",
        "version": "01.04.00",
        "area": "system",
        "description": "GitHub self-update, резервная копия, проверка, перезапуск и история.",
        "last_update": "Архив и версия обновления закреплены на одном точном GitHub commit SHA; сохранён rollback.",
        "depends_on": [],
    },
)


def module_registry() -> list[dict[str, Any]]:
    return [dict(item) for item in MODULE_REGISTRY]
